### ISSUE TITLE
Object types

### ISSUE THREAD

**Issue by woutersf** [archimodel/archimodel-net#2]
Hi there,

Love the tool. 
I'm missing the application component
<img width="137" alt="image" src="https://user-images.githubusercontent.com/592312/224429469-f192df76-5ca2-4ba7-8498-abe48eca6ac3.png">

**Comment by vbo75** [comment]
Hi,

Major archimate core layer elements (including application component) will be available in next release (expected soon).

**Comment by vbo75** [comment]
Hi,

A new version is available with a wide range of archimate components.
